---
services:

    _defaults:
        autoconfigure: true
        autowire: true
        public: true

    PhpTuf\ComposerStagerConsole\:
        resource: '../src/*'
        public: true
        exclude:
            - '../src/Console/Output'

    PhpTuf\ComposerStager\:
        resource: '../vendor/php-tuf/composer-stager/src/*'
        public: true
        exclude:
            - '../vendor/php-tuf/composer-stager/src/*/*/Value'
            - '../vendor/php-tuf/composer-stager/src/API/Exception'

    Symfony\Component\Filesystem\Filesystem: ~
    Symfony\Component\Process\ExecutableFinder: ~
