---
services:

    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    PhpTuf\ComposerStager\:
        resource: '../src/*'
        public: true

    PhpTuf\ComposerStager\Domain\BeginnerInterface:
        class: PhpTuf\ComposerStager\Domain\Beginner
    PhpTuf\ComposerStager\Domain\CleanerInterface:
        class: PhpTuf\ComposerStager\Domain\Cleaner
    PhpTuf\ComposerStager\Domain\CommitterInterface:
        class: PhpTuf\ComposerStager\Domain\Committer
    PhpTuf\ComposerStager\Domain\StagerInterface:
        class: PhpTuf\ComposerStager\Domain\Stager
    PhpTuf\ComposerStager\Infrastructure\FileSyncer\FileSyncerFactory:
        arguments:
            $phpFileSyncer: '@PhpTuf\ComposerStager\Infrastructure\FileSyncer\PhpFileSyncer'
            $rsyncFileSyncer: '@PhpTuf\ComposerStager\Infrastructure\FileSyncer\RsyncFileSyncer'
    PhpTuf\ComposerStager\Infrastructure\FileSyncer\FileSyncerInterface:
        factory: [ '@PhpTuf\ComposerStager\Infrastructure\FileSyncer\FileSyncerFactory', 'create' ]
    PhpTuf\ComposerStager\Infrastructure\FileSyncer\PhpFileSyncer: ~
    PhpTuf\ComposerStager\Infrastructure\FileSyncer\PhpFileSyncerInterface:
        class: PhpTuf\ComposerStager\Infrastructure\FileSyncer\PhpFileSyncer
    PhpTuf\ComposerStager\Infrastructure\FileSyncer\RsyncFileSyncer: ~
    PhpTuf\ComposerStager\Infrastructure\FileSyncer\RsyncFileSyncerInterface:
        class: PhpTuf\ComposerStager\Infrastructure\FileSyncer\RsyncFileSyncer
    PhpTuf\ComposerStager\Infrastructure\Filesystem\FilesystemInterface:
        class: PhpTuf\ComposerStager\Infrastructure\Filesystem\Filesystem
    PhpTuf\ComposerStager\Infrastructure\Process\ExecutableFinderInterface:
        class: PhpTuf\ComposerStager\Infrastructure\Process\ExecutableFinder
    PhpTuf\ComposerStager\Infrastructure\Process\Runner\ComposerRunnerInterface:
        class: PhpTuf\ComposerStager\Infrastructure\Process\Runner\ComposerRunner
    PhpTuf\ComposerStager\Infrastructure\Process\ProcessFactoryInterface:
        class: PhpTuf\ComposerStager\Infrastructure\Process\ProcessFactory
    PhpTuf\ComposerStager\Infrastructure\Process\Runner\RsyncRunnerInterface:
        class: PhpTuf\ComposerStager\Infrastructure\Process\Runner\RsyncRunner

    Symfony\Component\Filesystem\Filesystem: ~
    Symfony\Component\Finder\Finder: ~
    Symfony\Component\Process\ExecutableFinder: ~
