---
name: Main

on:
    push:
        branches: [ main, develop, wip ]
        paths-ignore:
            - .idea/**
            - docs/**
    pull_request:
        branches: [ main ]
        paths-ignore:
            - .idea/**
            - docs/**
    schedule:
        # Every Monday at 00:00:00 UTC.
        # @see https://crontab.cronhub.io/
        -   cron: "0 0 * * 1"

jobs:
    quality_check:
        name: "Quality Check"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ "8.1" ]
        steps:
            -   name: "Set up PHP"
                uses: shivammathur/setup-php@v2 # https://github.com/marketplace/actions/setup-php-action
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: none

            -   name: "Checkout code"
                uses: actions/checkout@v3 # https://github.com/marketplace/actions/checkout

            -   name: "Install dependencies"
                uses: ramsey/composer-install@v2 # https://github.com/marketplace/actions/install-composer-dependencies

            -   name: "Run all quality checks"
                run: "composer static"

    tests:
        name: "Test: ${{ matrix.os }} (${{ matrix.php }})"
        runs-on: "${{ matrix.os }}"
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest, macos-latest, windows-latest ]
                php: [ "8.1" ]
        steps:
            -   name: "Debugging info"
                run: "rsync --version | head -1"
                if: ${{ matrix.os != 'windows-latest' }}

            -   name: "Set up PHP"
                uses: shivammathur/setup-php@v2 # https://github.com/marketplace/actions/setup-php-action
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: none

            -   name: "Checkout code"
                uses: actions/checkout@v3 # https://github.com/marketplace/actions/checkout

            -   name: "Install dependencies"
                uses: ramsey/composer-install@v2 # https://github.com/marketplace/actions/install-composer-dependencies

            -   name: "Run tests"
                run: "composer phpunit"
